[package]
name = "factography_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
factography_core = { path = "../factography_core" }

syn = { version = "*", features = ["extra-traits", "full"] }
quote = "*"
proc-macro2 = "*"
